Collinear quark Changes
PcAux-Package/PcAux pull request #5
Opened 2017-01-27 22:44 UTC by vibhutittu

Modified the cleanCollinVars method.

2017-01-31 16:35 UTC, kylelang requested changes
In addition to the specific changes requested in the embedded comments, please format your code to conform to the official style guide, and please remove the 'Experiment' directory.

2017-01-31 16:35 UTC, kylelang commented on source/quark/R/01_QuarkData.R
> +    }else
Put 'else if' on a single line.

2017-01-31 16:35 UTC, kylelang commented on source/quark/R/01_QuarkData.R
> +        collinVars <- x
You must use the deep assignment operator '<<-' to assign values to the fields of a reference class object. The normal assignment operator '<-' will only make a local assignment when employed within a reference class method (i.e., the underlying field is not modified). 

Please change line 478 to 'collinVars <<- x'

2017-01-31 16:35 UTC, kylelang commented on source/quark/R/01_QuarkData.R
> +    naCount <-sapply(data,function(c) sum(length(which(is.na(c)))))
You don't need to count NAs. Use the complement of the 'respCounts' field.

2017-02-08 15:48 UTC, kylelang requested changes

2017-02-08 15:48 UTC, kylelang commented on source/quark/R/01_QuarkData.R
> +			     sameNaCntVec = "vector",
Do these three objects need to be fields in the QuarkData object? It looks like they are only used locally in the cleanCollinVars() function. Do they need to persist after cleanCollinVars() returns? If not please remove these fields and treat these variables as local.

2017-02-08 15:48 UTC, kylelang commented on source/quark/R/01_QuarkData.R
> +        maxNaCountValue  <- max(respCounts[maxVarCommon])
The 'respCounts' field is a vector of variablewise response rates (i.e., the complement of the variablewise missing data rates). This line will find the variable for which maxVarCommon == TRUE with the least missing data. Is that what you intend?

2017-02-08 15:48 UTC, kylelang commented on source/quark/R/01_QuarkData.R
> +        vector     <- c(sameNaCntVec,diffNaCntVec, diffMaxCntVec)
'vector' is the name of a built-in R function (i.e., the one that creates vectors). We don't want to use extant function names as variable names. Please rename this variable.

2017-02-08 19:14 UTC, vibhutittu commented on source/quark/R/01_QuarkData.R
> +			     sameNaCntVec = "vector",
Yes these three variables are used locally inside cleanCollinVars(). They will not persist after cleanCollinVars() but they need to be initialised locally . So shall I initilaize them locally inside the method cleanCollinVars()

2017-02-08 19:26 UTC, vibhutittu commented on source/quark/R/01_QuarkData.R
> +        maxNaCountValue  <- max(respCounts[maxVarCommon])
I am finding the variables in "maxVarCommon" that exist in both respCounts and maxVarCounts and then the maximum missing count value out of those and store in maxNaCountValue.

2017-02-08 19:26 UTC, vibhutittu commented on source/quark/R/01_QuarkData.R
> +        vector     <- c(sameNaCntVec,diffNaCntVec, diffMaxCntVec)
Ok I will rename it.

2017-02-09 16:05 UTC, kylelang approved these changes

2017-02-09 16:24 UTC, merged